### PR TITLE
Added Subgraph docs

### PR DESCRIPTION
**Pull request by PaulieB14**

### CODE REVIEW

**Comment by PaulieB14** [comment]
@vshvsh Please let me know if this works for you

**Comment by kolyasapphire** [comment]
Hi @PaulieB14 thanks for the PR! Some things need to be changed:

1. Structure is wrong: there is already a Subgraph page at `docs/docs/integrations/subgraph.md`, lets put everything there on one page.
2. You left mentions of Sablier, Juicebox, Connext all around the place, even full pages for other projects.
4. There is no need to write out every single entity, a link to https://github.com/lidofinance/lido-subgraph/blob/master/schema.graphql where data is always up to date is enough. We have so many entities that it would be a pain to read and maintain.
5. Code repo is https://github.com/lidofinance/lido-subgraph/

Best if you redo the PR in one commit and hard push the branch so git history is clean.

**Comment by PaulieB14** [comment]
@kolysapphire. Thanks for the feedback.  I will cancel this PR and make corrections in one commit on a new PR.  Thank you

**Comment by kolyasapphire** [comment]
Thanks! You can actually just roll back your local fork repo, make changes and force push your branch - no need for a new PR

**Comment by PaulieB14** [comment]
@kolyasapphire - sorry I canceled prior to this message.  Apologies, I'm new to this and obviously learning.  I appreciate you working w/ me.  Sorry for additional work.

**Comment by kolyasapphire** [comment]
No worries! Will have a look

**Pull request closed without merging**
