### PR TITLE
Update wording in the fail conditions documentation

### PR DESCRIPTION
**Pull request by flanagansteve**

### CODE REVIEW

**Comment by flanagansteve** [comment]
@TheDZhon what do you think?

**Comment by ujenjt** [comment]
LGTM

**Review by kadmil — APPROVED** [review]
LGTM

**Comment by kadmil** [comment]
Merged, thank you for contribution!

**Comment by flanagansteve** [comment]
> Merged, thank you for contribution!

Thank _you_ Victor!

**Pull request merged**
